spring.datasource.url=${jdbc.url:jdbc:mariadb://localhost:55432/jooq_demo}?allowMultiQueries=true
spring.datasource.username=${jdbc.user:jooq}
spring.datasource.password=${jdbc.password:jooq}
spring.jooq.sql-dialect=MARIADB
spring.flyway.enabled=false
